import NextAuth from 'next-auth'
import { authOptions } from '@/lib/auth'

/**
 * NextAuth v4 — catch-all route handler.
 *
 * Handles all /api/auth/* requests generated by the NextAuth flow:
 *
 *   GET  /api/auth/signin              — sign-in page redirect
 *   GET  /api/auth/signout             — sign-out page redirect
 *   GET  /api/auth/session             — session data (used by useSession)
 *   GET  /api/auth/csrf                — CSRF token
 *   GET  /api/auth/providers           — list of configured OAuth providers
 *   GET  /api/auth/callback/google     — OAuth callback after Google auth
 *   POST /api/auth/signin/google       — initiates the Google OAuth flow
 *   POST /api/auth/signout             — clears the session cookie
 *
 * authOptions are defined in lib/auth.ts and imported here to keep the route
 * file minimal and the config easily testable in isolation.
 */
const handler = NextAuth(authOptions)

export { handler as GET, handler as POST }
